# Generated by Django 3.2 on 2022-05-11 16:53

import core.utilities
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Outfit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(default=0, max_length=40, verbose_name="Образ"),
                ),
                ("price", models.FloatField(default=0, verbose_name="Цена")),
                (
                    "image",
                    models.ImageField(
                        upload_to=core.utilities.get_timestamp_path,
                        verbose_name="Изображение",
                    ),
                ),
            ],
        ),
    ]
