# Generated by Django 3.2 on 2022-05-11 16:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="outfit",
            name="author",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="my_outfits",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Автор образа",
            ),
        ),
        migrations.AddField(
            model_name="outfit",
            name="likes",
            field=models.ManyToManyField(
                blank=True, related_name="outfits", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
