# Generated by Django 3.2 on 2022-05-19 08:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_auto_20220519_0804"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="viewed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Viewed by",
            ),
        ),
    ]
